// Installation commands shown on /install. Every command here mirrors the
// real repos on github.com/infrahubcenter: infrahub-deploy (deploy/docker,
// deploy/kubernetes), the agent install commands generated by
// infrahub-api/internal/services/*_agent_install.go, and
// infrahub-vm-agent/install.sh. Images live on
// docker.io/infrahubcenter.

export const GO_VERSION = "1.26.0";
export const VERSION = "1.0.0";
export const GITHUB = "https://github.com/infrahubcenter";
export const REPO_URL = `${GITHUB}/infrahub-deploy.git`;
const RAW = "https://raw.githubusercontent.com/infrahubcenter";
export const DEPLOY_RAW = `${RAW}/infrahub-deploy/main/deploy`;

export const IMAGES: { name: string; role: string }[] = [
  { name: "infrahubcenter/infrahub-api", role: "Go API, schedulers, migrations (runs them on start)" },
  { name: "infrahubcenter/infrahub-ui", role: "Web console" },
  { name: "infrahubcenter/infrahub-gateway", role: "nginx entry point: /api → API, / → console" },
  { name: "infrahubcenter/infrahub-docker-agent", role: "Agent for Docker hosts" },
  { name: "infrahubcenter/infrahub-vm-agent", role: "Agent for Linux VMs (metrics + journal logs)" },
  { name: "infrahubcenter/infrahub-k8s-agent", role: "In-cluster Kubernetes agent" },
];

export type Distro = {
  id: string;
  label: string;
  hint: string;
  code: string;
  note?: string;
};

// --- Docker Engine + Compose plugin, per distro (Docker's official repos) ---
export const DOCKER_ENGINE: Distro[] = [
  {
    id: "ubuntu",
    label: "Ubuntu",
    hint: "apt · .deb · 22.04 / 24.04",
    code: `sudo apt-get update
sudo apt-get install -y ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \\
  https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \\
  | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl enable --now docker`,
  },
  {
    id: "debian",
    label: "Debian",
    hint: "apt · .deb · 11 / 12",
    code: `sudo apt-get update
sudo apt-get install -y ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \\
  https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \\
  | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl enable --now docker`,
  },
  {
    id: "rhel",
    label: "Red Hat Enterprise Linux",
    hint: "dnf · .rpm · RHEL 8 / 9",
    code: `sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl enable --now docker`,
    note: "If Podman is preinstalled, remove it first: sudo dnf remove -y podman buildah runc",
  },
  {
    id: "rocky",
    label: "Rocky / AlmaLinux / CentOS Stream",
    hint: "dnf · .rpm · 8 / 9",
    code: `sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl enable --now docker`,
  },
  {
    id: "fedora",
    label: "Fedora",
    hint: "dnf · .rpm",
    code: `sudo dnf -y install dnf-plugins-core
# Fedora 41+ (dnf5):
sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
# Fedora 40 and older: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl enable --now docker`,
  },
  {
    id: "al2023",
    label: "Amazon Linux 2023",
    hint: "dnf · .rpm",
    code: `sudo dnf install -y docker
sudo systemctl enable --now docker
# Compose v2 plugin (not packaged on AL2023):
sudo mkdir -p /usr/local/lib/docker/cli-plugins
sudo curl -fsSL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m)" \\
  -o /usr/local/lib/docker/cli-plugins/docker-compose
sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose`,
  },
  {
    id: "yum",
    label: "CentOS 7 / Amazon Linux 2",
    hint: "yum · .rpm · legacy",
    code: `# CentOS 7
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Amazon Linux 2
sudo yum install -y docker

sudo systemctl enable --now docker`,
    note: "CentOS 7 is end-of-life. Fine for running agents; for the platform itself prefer a supported distro.",
  },
  {
    id: "suse",
    label: "SUSE / openSUSE",
    hint: "zypper · .rpm",
    code: `sudo zypper --non-interactive install docker docker-compose
sudo systemctl enable --now docker`,
  },
];

export const DOCKER_POSTINSTALL = `# Optional: run docker without sudo (log out and back in afterwards)
sudo usermod -aG docker $USER

docker version && docker compose version`;

// --- Platform via Docker Compose (published images, nothing built) ---
export const COMPOSE_STEPS: { title: string; body?: string; code: string; file?: string }[] = [
  {
    title: "Download the compose file and settings template",
    code: `mkdir -p ~/infrahub && cd ~/infrahub
curl -fsSLO ${DEPLOY_RAW}/docker/docker-compose.yml
curl -fsSL ${DEPLOY_RAW}/docker/.env.example -o .env`,
  },
  {
    title: "Generate secrets and set your address",
    body: "PUBLIC_URL must be the address browsers and agents use to reach this server -- its IP or domain, not localhost. The admin password needs at least 12 characters.",
    code: `sed -i "s|^POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=$(openssl rand -hex 24)|" .env
sed -i "s|^JWT_SECRET=.*|JWT_SECRET=$(openssl rand -hex 48)|" .env
sed -i "s|^SSH_CREDENTIAL_ENCRYPTION_KEY=.*|SSH_CREDENTIAL_ENCRYPTION_KEY=$(openssl rand -base64 32)|" .env
sed -i "s|^PUBLIC_URL=.*|PUBLIC_URL=http://$(hostname -I | awk '{print $1}')|" .env

# Then set BOOTSTRAP_ADMIN_EMAIL and BOOTSTRAP_ADMIN_PASSWORD (and INFRAHUB_PLAN):
nano .env
chmod 600 .env`,
  },
  {
    title: "Start the platform",
    body: "On first start the API migrates and seeds the database and creates your admin account automatically.",
    code: `docker compose up -d
docker compose ps

curl -s http://localhost/api/health      # {"status":"ok","database":"ok"}
# Open PUBLIC_URL in a browser and sign in with BOOTSTRAP_ADMIN_EMAIL / _PASSWORD.`,
  },
  {
    title: "Upgrade later",
    code: `sed -i "s|^INFRAHUB_VERSION=.*|INFRAHUB_VERSION=<new-version>|" .env
docker compose pull && docker compose up -d`,
  },
];

// --- Platform on Kubernetes ---
export const K8S_STEPS: { title: string; body?: string; code: string; file?: string }[] = [
  {
    title: "Create the namespace and secrets",
    code: `kubectl create namespace infrahub
kubectl -n infrahub create secret generic infrahub-secrets \\
  --from-literal=postgres-password="$(openssl rand -hex 24)" \\
  --from-literal=jwt-secret="$(openssl rand -hex 48)" \\
  --from-literal=ssh-credential-encryption-key="$(openssl rand -base64 32)" \\
  --from-literal=bootstrap-admin-password='<first-admin-password>'`,
  },
  {
    title: "Download and edit the manifest",
    body: "Set PUBLIC_URL (the address of the gateway -- load balancer IP or domain) and BOOTSTRAP_ADMIN_EMAIL in the infrahub-config ConfigMap.",
    code: `curl -fsSLO ${DEPLOY_RAW}/kubernetes/infrahub.yaml
nano infrahub.yaml`,
  },
  {
    title: "Deploy",
    body: "PostgreSQL (StatefulSet with a 10 Gi volume), API, console and gateway. The gateway Service is type LoadBalancer; use ingress.yaml instead if you run an Ingress controller.",
    code: `kubectl apply -f infrahub.yaml
kubectl -n infrahub rollout status deploy/infrahub-api --timeout=5m
kubectl -n infrahub get svc infrahub-gateway     # EXTERNAL-IP = your PUBLIC_URL host

# Optional Ingress (ingress-nginx + your domain):
curl -fsSLO ${DEPLOY_RAW}/kubernetes/ingress.yaml`,
  },
];

// --- Platform directly on a Linux host (systemd, no Docker) ---
export const HOST_PREREQS: Distro[] = [
  {
    id: "apt",
    label: "Ubuntu / Debian",
    hint: "apt · .deb",
    code: `sudo apt-get update
sudo apt-get install -y git curl ca-certificates build-essential openssl nginx

# PostgreSQL 16 (official PGDG repo)
sudo apt-get install -y postgresql-common
sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
sudo apt-get install -y postgresql-16
sudo systemctl enable --now postgresql

# Node.js 22
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
sudo apt-get install -y nodejs

# Firewall (if ufw is enabled)
sudo ufw allow 'Nginx Full'`,
  },
  {
    id: "dnf",
    label: "RHEL / Rocky / AlmaLinux",
    hint: "dnf · .rpm · 8 / 9",
    code: `sudo dnf install -y git curl gcc make openssl tar nginx

# PostgreSQL 16 (official PGDG repo)
sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-$(rpm -E %rhel)-x86_64/pgdg-redhat-repo-latest.noarch.rpm
sudo dnf -qy module disable postgresql
sudo dnf install -y postgresql16-server
sudo /usr/pgsql-16/bin/postgresql-16-setup initdb
sudo systemctl enable --now postgresql-16

# Node.js 22
curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo bash -
sudo dnf install -y nodejs

# Firewall + SELinux (lets nginx proxy to the local API/UI ports)
sudo firewall-cmd --permanent --add-service=http --add-service=https && sudo firewall-cmd --reload
sudo setsebool -P httpd_can_network_connect 1`,
  },
  {
    id: "al2023",
    label: "Amazon Linux 2023 / Fedora",
    hint: "dnf · .rpm",
    code: `sudo dnf install -y git gcc make openssl tar nginx nodejs22 postgresql16-server
sudo postgresql-setup --initdb
# Allow password logins over localhost TCP (default is ident):
sudo sed -i -E 's/^(host\\s+all\\s+all\\s+(127\\.0\\.0\\.1\\/32|::1\\/128)\\s+)ident/\\1scram-sha-256/' /var/lib/pgsql/data/pg_hba.conf
sudo systemctl enable --now postgresql`,
    note: "On Fedora, install nodejs instead of nodejs22 if that package name isn't available.",
  },
  {
    id: "yum",
    label: "CentOS 7 / Amazon Linux 2",
    hint: "yum · .rpm · legacy",
    code: `# Not supported for the platform itself:
# Node.js 20+ requires glibc 2.28, and these distros ship glibc 2.17.
# Use the Docker Compose method on these hosts instead,
# or run the platform on a supported distro and install only agents here.`,
  },
];

export const HOST_COMMON: { title: string; body?: string; code: string; file?: string }[] = [
  {
    title: "Install Go",
    body: "Distro Go packages are usually too old; the API needs Go 1.26+.",
    code: `curl -fsSL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz | sudo tar -C /usr/local -xz
export PATH=$PATH:/usr/local/go/bin
go version`,
  },
  {
    title: "Create the service user, database and get the source",
    code: `sudo useradd --system --create-home --home-dir /opt/infrahub --shell /usr/sbin/nologin infrahub
sudo git clone ${GITHUB}/infrahub-api.git /opt/infrahub/src/infrahub-api
sudo git clone ${GITHUB}/infrahub-ui.git  /opt/infrahub/src/infrahub-ui

sudo -u postgres psql -c "CREATE USER infrahub WITH PASSWORD '<db-password>';"
sudo -u postgres psql -c "CREATE DATABASE infrahub OWNER infrahub;"`,
  },
  {
    title: "Build the API",
    code: `cd /opt/infrahub/src/infrahub-api
sudo mkdir -p /opt/infrahub/api
for c in server migrate seed bootstrap-admin gen-encryption-key encrypt-config-value; do
  sudo CGO_ENABLED=0 /usr/local/go/bin/go build -trimpath -ldflags="-s -w" -o /opt/infrahub/api/$c ./cmd/$c
done
sudo cp -r migrations production.ini.enc /opt/infrahub/api/`,
  },
  {
    title: "Generate secrets and configure",
    body: "Paste each ENC(...) value into /opt/infrahub/api/production.ini.enc (DATABASE_URL, JWT_SECRET, SSH_CREDENTIAL_ENCRYPTION_KEY, BOOTSTRAP_ADMIN_*), and set PUBLIC_URL to your domain.",
    code: `cd /opt/infrahub/api
export INFRAHUB_MASTER_KEY=$(./gen-encryption-key)

sudo install -d -m 0750 -o root -g infrahub /etc/infrahub
echo "INFRAHUB_MASTER_KEY=$INFRAHUB_MASTER_KEY" | sudo tee /etc/infrahub/api.env > /dev/null
sudo chmod 0640 /etc/infrahub/api.env && sudo chgrp infrahub /etc/infrahub/api.env

./encrypt-config-value 'postgres://infrahub:<db-password>@localhost:5432/infrahub?sslmode=disable'  # DATABASE_URL
./encrypt-config-value "$(openssl rand -base64 48)"                                                # JWT_SECRET
./encrypt-config-value "$(./gen-encryption-key)"                                                   # SSH_CREDENTIAL_ENCRYPTION_KEY
./encrypt-config-value '<first-admin-password>'                                                     # BOOTSTRAP_ADMIN_PASSWORD

sudo -E nano /opt/infrahub/api/production.ini.enc`,
  },
  {
    title: "Migrate, seed and create the first admin",
    code: `cd /opt/infrahub/api
sudo -u infrahub env APP_ENV=production INFRAHUB_MASTER_KEY=$INFRAHUB_MASTER_KEY ./migrate up
sudo -u infrahub env APP_ENV=production INFRAHUB_MASTER_KEY=$INFRAHUB_MASTER_KEY ./seed
sudo -u infrahub env APP_ENV=production INFRAHUB_MASTER_KEY=$INFRAHUB_MASTER_KEY ./bootstrap-admin
sudo chown -R infrahub:infrahub /opt/infrahub`,
  },
  {
    title: "Build the console",
    body: "NEXT_PUBLIC_API_BASE_URL is baked in at build time -- rebuild if your domain changes.",
    code: `cd /opt/infrahub/src/infrahub-ui
npm ci
NEXT_PUBLIC_API_BASE_URL=https://infrahub.example.com npm run build

sudo mkdir -p /opt/infrahub/ui/.next
sudo cp -r .next/standalone/. /opt/infrahub/ui/
sudo cp -r public /opt/infrahub/ui/public
sudo cp -r .next/static /opt/infrahub/ui/.next/static
sudo chown -R infrahub:infrahub /opt/infrahub/ui`,
  },
  {
    title: "systemd units",
    file: "/etc/systemd/system/infrahub-api.service  +  infrahub-ui.service",
    code: `sudo tee /etc/systemd/system/infrahub-api.service > /dev/null <<'EOF'
[Unit]
Description=Infra Hub Center API
After=network-online.target postgresql.service postgresql-16.service
Wants=network-online.target

[Service]
User=infrahub
WorkingDirectory=/opt/infrahub/api
Environment=APP_ENV=production
EnvironmentFile=/etc/infrahub/api.env
ExecStart=/opt/infrahub/api/server
Restart=always
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

sudo tee /etc/systemd/system/infrahub-ui.service > /dev/null <<'EOF'
[Unit]
Description=Infra Hub Center Console
After=network-online.target infrahub-api.service

[Service]
User=infrahub
WorkingDirectory=/opt/infrahub/ui
Environment=NODE_ENV=production PORT=3000 HOSTNAME=127.0.0.1 INFRAHUB_PLAN=community
ExecStart=/usr/bin/node /opt/infrahub/ui/server.js
Restart=always
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now infrahub-api infrahub-ui`,
  },
  {
    title: "nginx reverse proxy",
    body: "One origin: /api/* (including WebSockets for console, live logs and agents) goes to the API, everything else to the console. Add TLS with certbot --nginx.",
    file: "/etc/nginx/conf.d/infrahub.conf",
    code: `sudo tee /etc/nginx/conf.d/infrahub.conf > /dev/null <<'EOF'
map $http_upgrade $connection_upgrade { default upgrade; '' close; }

server {
    listen 80;
    server_name infrahub.example.com;
    client_max_body_size 50m;

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 1h;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF

sudo nginx -t && sudo systemctl enable --now nginx && sudo systemctl reload nginx
curl -s http://localhost/api/health`,
  },
];

// --- Agents ---
export const AGENT_DOCKER_HOST = `# Console: Agents & Integrations → Docker Host Onboarding → Install Agent
# copies this exact command with your backend URL and a one-time token:
docker run -d --name infrahub-docker-agent --restart unless-stopped \\
  -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/host/proc:ro -v /:/host/root:ro \\
  -e INFRAHUB_BACKEND_URL='<backend-url>' -e INFRAHUB_AGENT_TOKEN='<token>' \\
  docker.io/infrahubcenter/infrahub-docker-agent:${VERSION}`;

export const AGENT_VM_DOCKER = `# Console: Compute → Host Metrics & Logs → Configure → VM Agent
docker run -d --name infrahub-vm-agent --restart unless-stopped \\
  -v /proc:/host/proc:ro -v /:/host/root:ro \\
  -v /var/log:/host/var/log:ro -v /var/log/journal:/host/var/log/journal:ro -v /run/log/journal:/host/run/log/journal:ro \\
  -e INFRAHUB_BACKEND_URL='<backend-url>' -e INFRAHUB_AGENT_TOKEN='<token>' -e INFRAHUB_METRICS_INTERVAL=15 \\
  docker.io/infrahubcenter/infrahub-vm-agent:${VERSION}`;

export const AGENT_VM_NATIVE = `# apt (Ubuntu/Debian), dnf (RHEL/Rocky/Alma/Fedora/Amazon Linux 2023),
# yum (CentOS 7/Amazon Linux 2), zypper (SUSE/openSUSE). Installs a systemd service.
curl -fsSL ${RAW}/infrahub-vm-agent/main/install.sh \\
  | sudo bash -s -- --backend-url '<backend-url>' --token '<token>'

systemctl status infrahub-vm-agent
journalctl -u infrahub-vm-agent -f

# Remove:
curl -fsSL ${RAW}/infrahub-vm-agent/main/install.sh | sudo bash -s -- --uninstall`;

export const AGENT_K8S = `# Console: Agents & Integrations → Kubernetes Cluster Onboarding → Connect Cluster
# shows your backend URL and a one-time token. Then, in the cluster to monitor:
kubectl create namespace infrahub-agent
kubectl create secret generic infrahub-k8s-agent -n infrahub-agent \\
  --from-literal=backend-url='<backend-url>' \\
  --from-literal=agent-token='<token>'
kubectl apply -f ${RAW}/infrahub-k8s-agent/main/deploy/manifest.yaml

kubectl -n infrahub-agent get pods`;
